global using Deopeia.Common;
global using Deopeia.Common.Infrastructure;
global using Deopeia.Common.Infrastructure.Comparers;
global using Deopeia.Common.Infrastructure.Converters;
global using Deopeia.Common.Infrastructure.Localization;
global using Deopeia.Identity.Domain;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
