version: '3.8'

services:
  minio:
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - viriplaca-minio:/data
    command: server --console-address ':9001' --json /data

  mssql:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@word
    ports:
      - "1433:1433"
    volumes:
      - viriplaca-mssql:/var/opt/mssql

  nginx:
    ports:
      - "8080:80"
    volumes:
      - ./build/nginx/conf.d:/etc/nginx/conf.d

  viriplaca.hr.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=mssql;Database=ViriplacaHR;User Id=sa;Password=Pass@word;MultipleActiveResultSets=True;Encrypt=False;
      - MinIO__Endpoint=minio:9000
      - MinIO__AccessKey=3H5VDramzIBQeb7P3oZk
      - MinIO__SecretKey=Re0bAZyZnn9Oh2XvimrPo16vYgqZlWJxD2HtcBNW
    ports:
      - "7000:8080"

  viriplaca.identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=mssql;Database=ViriplacaIdentity;User Id=sa;Password=Pass@word;MultipleActiveResultSets=True;Encrypt=False;
      - Jwt__Key=ZjKhHulSM6xza/11Uhi+j7B5ofJhK/MVgXM81azghJh15FsVxYuIv33TbcBP95fy
      - Jwt__Issuer=https://localhost:7002
      - MinIO__Endpoint=minio:9000
      - MinIO__AccessKey=3H5VDramzIBQeb7P3oZk
      - MinIO__SecretKey=Re0bAZyZnn9Oh2XvimrPo16vYgqZlWJxD2HtcBNW
    ports:
      - "7001:8080"
      - "7002:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
volumes:
  viriplaca-minio: {}
  viriplaca-mssql: {}

