global using System.Data;
global using System.Globalization;
global using Dapper;
global using Deopeia.Common.Domain;
global using Deopeia.Common.Extensions;
global using Deopeia.Common.Infrastructure.Converters;
global using Deopeia.Common.Localization;
global using EFCore.BulkExtensions;
global using Microsoft.EntityFrameworkCore;
