global using Dapper;
global using Microsoft.EntityFrameworkCore;
global using System.Data;
global using System.Globalization;
global using System.Linq.Expressions;
global using Viriplaca.Common.Data.Converters;
global using Viriplaca.Common.Domain;
global using Viriplaca.Common.Extensions;
global using Viriplaca.Common.Localization;
